#!/usr/bin/env bash
set -Eeuo pipefail

# =============================================================================
# MiniMax H3 FUSED RefAV COMPLETE v1
#
# Purpose:
#   Fresh-Pod, one-shot MiniMax-H3 local environment with:
#     - MATLOWAI Fused FL2VA+Ref2VA + Turbo8 + Mystic0.7 INT8 ConvRot
#     - Kijai INT8 ConvRot video VAE
#     - MiniMax H3 NVFP4-AWQ text encoder + FP32 audio VAE
#     - SLA sparse attention node
#     - Official MATLOWAI I2V/FL2V + Ref2VA workflows
#     - 05A: one MP4 -> motion frames + embedded audio reference
#     - 05B: reference video -> motion, separate audio -> voice/whisper reference
#
# Isolation / safety:
#   - Installs independently to /workspace/runpod-slim/ComfyUI-H3-Fused-RefAV
#   - Does NOT overwrite /workspace/runpod-slim/ComfyUI-H3-Fused
#   - Port 8188 is handed over only after setup completes
#
# Recommended RunPod:
#   RTX 5090 + NVIDIA Driver >= 580 + CUDA 13 capable host.
# =============================================================================

ROOT="${ROOT:-/workspace/runpod-slim}"
COMFY="${COMFY:-$ROOT/ComfyUI-H3-Fused-RefAV}"
PORT="${PORT:-8188}"
COMFY_TAG="${COMFY_TAG:-v0.34.0}"
PYTHON_BIN="${PYTHON_BIN:-python3.12}"
LOG_DIR="$COMFY/setup_logs"
RUNTIME_DIR="$COMFY/runtime_logs"
WF_DIR="$COMFY/user/default/workflows"
STATE_DIR="$ROOT/.h3_fused_refav_complete_v1"

MODEL="minimax_h3_fused_refdelta_r1024_turbo8_mystic07_int8_convrot.safetensors"
TEXT="qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors"
VIDEO_VAE="minimax_h3_video_vae_int8_convrot.safetensors"
AUDIO_VAE="minimax_h3_audio_vae_fp32.safetensors"

MODEL_URL="https://huggingface.co/MATLOWAI/minimax-h3-fused-turbo-int8-convrot/resolve/main/diffusion_models/$MODEL?download=true"
TEXT_URL="https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/text_encoders/$TEXT?download=true"
VIDEO_VAE_URL="https://huggingface.co/Kijai/MiniMax-H3-experimental/resolve/main/$VIDEO_VAE?download=true"
AUDIO_VAE_URL="https://huggingface.co/Comfy-Org/MiniMax-H3/resolve/main/vae/$AUDIO_VAE?download=true"

MODEL_SHA="4262e4e9963c553fa00016bbe83961407a4fc0a888be95fd836c8d4f2304e48b"
TEXT_SHA="35a88d51044231fe332301d7a62aa81e3f2cba62febeb446e2c1e3e0ef76f2c6"
VIDEO_VAE_SHA="9bb2d96f218c76babd85e0611b85ca8fb330a90546c01a0005e8a58a59593410"
AUDIO_VAE_SHA="8e505d95dd1561d47abd43d4238fd40d9bb1ae9e147ed0a4cba778d76ae4db48"

WF_I2V="01_FUSED_H3_I2V_FL2V_4STEP_SLA.json"
WF_REF="02_FUSED_H3_REF2VA_4STEP_SLA.json"
WF_I2V_URL="https://huggingface.co/MATLOWAI/minimax-h3-fused-turbo-int8-convrot/resolve/main/workflows/04_i2v_fl2v_4step_sla.json?download=true"
WF_REF_URL="https://huggingface.co/MATLOWAI/minimax-h3-fused-turbo-int8-convrot/resolve/main/workflows/05_ref2va_4step_sla.json?download=true"

WF_REFA="05A_FUSED_H3_REF_MP4_MOTION_AUDIO_4STEP_SLA.json"
WF_REFB="05B_FUSED_H3_REF_VIDEO_PLUS_SEPARATE_AUDIO_4STEP_SLA.json"

SLA_REPO="https://github.com/ethanfel/ComfyUI-PlagueKind-Nodes-only-sparse.git"
MAINODES_REPO="https://github.com/matlowai/ComfyUI-MAINodes.git"

green(){ printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[0;33m%s\033[0m\n' "$*"; }
red(){ printf '\033[0;31m%s\033[0m\n' "$*"; }
die(){ red "[FAILED] $*"; exit 1; }

mkdir -p "$ROOT" "$STATE_DIR"

on_error(){
  rc=$?
  line="${BASH_LINENO[0]:-unknown}"
  red ""
  red "H3 FUSED RefAV COMPLETE FAILED rc=$rc line=$line"
  if [[ -d "$RUNTIME_DIR" ]]; then
    latest="$(ls -t "$RUNTIME_DIR"/comfy_*.log 2>/dev/null | head -1 || true)"
    [[ -n "${latest:-}" ]] && { echo "Latest runtime log: $latest"; tail -120 "$latest" || true; }
  fi
  exit "$rc"
}
trap on_error ERR

echo "================================================================="
echo " MiniMax H3 FUSED RefAV COMPLETE v1"
echo "================================================================="
echo "Install dir: $COMFY"
echo "Port:        $PORT"
echo

# -----------------------------------------------------------------------------
# 1. Preflight
# -----------------------------------------------------------------------------
echo "[1/10] Preflight"

if ! command -v nvidia-smi >/dev/null 2>&1; then
  die "nvidia-smi not found"
fi

DRIVER="$(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1 | tr -d ' ')"
GPU="$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)"
echo "GPU:    $GPU"
echo "Driver: $DRIVER"

DRIVER_MAJOR="${DRIVER%%.*}"
if [[ "$DRIVER_MAJOR" =~ ^[0-9]+$ ]] && (( DRIVER_MAJOR < 580 )); then
  die "Driver $DRIVER is too old for the recommended CUDA 13 / RTX 5090 path. Select a RunPod host with Driver 580+."
fi

for tool in git curl aria2c lsof ffmpeg; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git curl aria2 lsof ffmpeg ca-certificates
    break
  fi
done
green "  ✓ system tools"

# -----------------------------------------------------------------------------
# 2. ComfyUI v0.34.0 independent checkout
# -----------------------------------------------------------------------------
echo "[2/10] ComfyUI $COMFY_TAG"

if [[ ! -d "$COMFY/.git" ]]; then
  if [[ -e "$COMFY" ]]; then
    mv "$COMFY" "${COMFY}.incomplete.$(date +%Y%m%d_%H%M%S)"
  fi
  git clone --depth 1 --branch "$COMFY_TAG" https://github.com/Comfy-Org/ComfyUI.git "$COMFY"
else
  git -C "$COMFY" fetch --depth 1 --force origin "refs/tags/$COMFY_TAG:refs/tags/$COMFY_TAG"
  git -C "$COMFY" checkout -f "$COMFY_TAG"
  git -C "$COMFY" reset --hard "$COMFY_TAG"
fi

grep -Rqs "MiniMaxH3ImageToVideo" "$COMFY/comfy_extras" || \
  die "$COMFY_TAG does not contain MiniMax-H3 core nodes"

mkdir -p "$LOG_DIR" "$RUNTIME_DIR" "$WF_DIR" \
  "$COMFY/models/diffusion_models" "$COMFY/models/text_encoders" "$COMFY/models/vae"

SETUP_LOG="$LOG_DIR/setup_$(date +%Y%m%d_%H%M%S).log"
exec > >(tee -a "$SETUP_LOG") 2>&1

green "  ✓ ComfyUI ready"

# -----------------------------------------------------------------------------
# 3. Python / CUDA stack
# -----------------------------------------------------------------------------
echo "[3/10] Python / CUDA stack"

if [[ ! -x "$COMFY/.venv/bin/python" ]]; then
  "$PYTHON_BIN" -m venv --system-site-packages "$COMFY/.venv"
fi
PY="$COMFY/.venv/bin/python"
PIP="$COMFY/.venv/bin/pip"

"$PY" -m pip install -q -U pip setuptools wheel

# Prevent requirements from silently replacing the GPU torch stack.
REQ_FILTERED="$STATE_DIR/requirements_no_torch.txt"
"$PY" - "$COMFY/requirements.txt" "$REQ_FILTERED" <<'PYCODE'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
pat = re.compile(r'^\s*(torch|torchvision|torchaudio)(?:\s*[<>=!~].*)?\s*(?:#.*)?$', re.I)
out=[]
for line in open(src, encoding='utf-8'):
    if not pat.match(line.strip()):
        out.append(line)
open(dst,'w',encoding='utf-8').writelines(out)
PYCODE

"$PIP" install -q --upgrade-strategy only-if-needed -r "$REQ_FILTERED"

# Reuse a CUDA 13 torch if available. Otherwise install official cu130 wheels.
if "$PY" - <<'PYCODE' >/tmp/h3_fused_torch_probe.txt 2>&1
import torch
ok = torch.cuda.is_available() and str(torch.version.cuda or "").startswith("13.")
print("torch=", torch.__version__)
print("torch_cuda=", torch.version.cuda)
print("cuda=", torch.cuda.is_available())
print("gpu=", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NONE")
raise SystemExit(0 if ok else 1)
PYCODE
then
  cat /tmp/h3_fused_torch_probe.txt
  echo "  [SKIP] usable CUDA 13 PyTorch already available"
else
  cat /tmp/h3_fused_torch_probe.txt || true
  echo "  Installing official CUDA 13 PyTorch..."
  "$PIP" install -q -U torch torchvision torchaudio \
    --extra-index-url https://download.pytorch.org/whl/cu130
fi

# INT8 ConvRot / Comfy quant backend.
"$PIP" install -q -U "comfy-kitchen[cublas]==0.2.31" triton

"$PY" - <<'PYCODE'
import torch
print("torch:", torch.__version__)
print("torch CUDA:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NONE")
assert torch.cuda.is_available()
assert str(torch.version.cuda or "").startswith("13."), "CUDA 13 PyTorch required for this saved 5090 path"
x=torch.randn((128,128), device="cuda")
print("CUDA probe:", float((x@x).mean()))
PYCODE
green "  ✓ CUDA 13 stack"

# -----------------------------------------------------------------------------
# 4. Required custom nodes
# -----------------------------------------------------------------------------
echo "[4/10] Custom nodes"

clone_or_update(){
  local repo="$1" dest="$2"
  if [[ ! -d "$dest/.git" ]]; then
    rm -rf "$dest"
    git clone --depth 1 "$repo" "$dest"
  else
    git -C "$dest" pull --ff-only
  fi
  if [[ -f "$dest/requirements.txt" ]]; then
    "$PIP" install -q -r "$dest/requirements.txt"
  fi
}

clone_or_update "$SLA_REPO" "$COMFY/custom_nodes/ComfyUI-PlagueKind-Nodes-only-sparse"
clone_or_update "$MAINODES_REPO" "$COMFY/custom_nodes/ComfyUI-MAINodes"

green "  ✓ SLA + MAINodes"

# -----------------------------------------------------------------------------
# 5. Verified downloader
# -----------------------------------------------------------------------------
verified_download(){
  local label="$1" url="$2" dest="$3" sha="$4" min_bytes="$5"
  mkdir -p "$(dirname "$dest")"

  if [[ -s "$dest" ]]; then
    size="$(stat -c%s "$dest")"
    if (( size >= min_bytes )); then
      got="$(sha256sum "$dest" | awk '{print $1}')"
      if [[ "$got" == "$sha" ]]; then
        echo "  [SKIP verified] $label"
        return 0
      fi
    fi
    yellow "  Existing $label is incomplete or checksum-mismatched; redownloading."
    rm -f "$dest" "$dest.aria2"
  fi

  echo "  [DOWNLOAD] $label"
  aria2c -c -x16 -s16 -k16M --file-allocation=none \
    --auto-file-renaming=false --allow-overwrite=true \
    --max-tries=12 --retry-wait=10 --summary-interval=15 \
    --dir "$(dirname "$dest")" --out "$(basename "$dest")" "$url"

  [[ -s "$dest" ]] || die "Download failed: $label"
  size="$(stat -c%s "$dest")"
  (( size >= min_bytes )) || die "$label too small: $size"
  got="$(sha256sum "$dest" | awk '{print $1}')"
  [[ "$got" == "$sha" ]] || die "$label SHA256 mismatch: $got"
  green "  ✓ $label"
}

# -----------------------------------------------------------------------------
# 6. Model files
# -----------------------------------------------------------------------------
echo "[5/10] Fused model"
verified_download "Fused H3 model" "$MODEL_URL" \
  "$COMFY/models/diffusion_models/$MODEL" "$MODEL_SHA" 20900000000

echo "[6/10] Text encoder + VAEs"
verified_download "Qwen3VL text encoder" "$TEXT_URL" \
  "$COMFY/models/text_encoders/$TEXT" "$TEXT_SHA" 14000000000
verified_download "INT8 ConvRot video VAE" "$VIDEO_VAE_URL" \
  "$COMFY/models/vae/$VIDEO_VAE" "$VIDEO_VAE_SHA" 3100000000
verified_download "FP32 audio VAE" "$AUDIO_VAE_URL" \
  "$COMFY/models/vae/$AUDIO_VAE" "$AUDIO_VAE_SHA" 500000000

# -----------------------------------------------------------------------------
# 7. Workflows: official + embedded RefAV variants
# -----------------------------------------------------------------------------
echo "[7/10] Workflows"

curl -fL --retry 8 --retry-all-errors --retry-delay 5 \
  "$WF_I2V_URL" -o "$WF_DIR/$WF_I2V"
curl -fL --retry 8 --retry-all-errors --retry-delay 5 \
  "$WF_REF_URL" -o "$WF_DIR/$WF_REF"

# 05A: one MP4 provides both motion frames and its embedded audio.
base64 -d > "$WF_DIR/$WF_REFA" <<'B64_05A'
ewogICJpZCI6ICJmMzc2YTY2Yi0xMzkzLTQ5MTMtYTk0Zi03NTI4NzQ5OWVlYTEiLAogICJyZXZpc2lvbiI6IDAsCiAgImxhc3Rfbm9kZV9pZCI6IDkwMywKICAibGFzdF9saW5rX2lkIjogMzAsCiAgIm5vZGVzIjogWwogICAgewogICAgICAiaWQiOiAxLAogICAgICAidHlwZSI6ICJQcmltaXRpdmVTdHJpbmdNdWx0aWxpbmUiLAogICAgICAicG9zIjogWwogICAgICAgIDQwLAogICAgICAgIDQwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDUwMCwKICAgICAgICAzNjAKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDAsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJTVFJJTkciLAogICAgICAgICAgInR5cGUiOiAiU1RSSU5HIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgNgogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIlBST01QVCDigJQgUGljdHVyZSAxID0gaWRlbnRpdHkgLyBSZWZlcmVuY2UgTVA0ID0gbW90aW9uICsgd2hpc3BlciB2b2ljZSIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJQcmltaXRpdmVTdHJpbmdNdWx0aWxpbmUiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAic3ViamVjdF9kZWZpbml0aW9uczpcbjxTdWJqZWN0IDE+IGlzIHRoZSBhZHVsdCBKYXBhbmVzZSBtYWxlIGluIDxQaWN0dXJlIDE+LiBIaXMgaWRlbnRpdHksIGJvZHkgYXBwZWFyYW5jZSwgY2xvdGhpbmcsIGFuZCB2aXN1YWwgY2hhcmFjdGVyaXN0aWNzIGZvbGxvdyA8UGljdHVyZSAxPi5cblxucmVmZXJlbmNlX3JvbGVzOlxuPFBpY3R1cmUgMT4gY29udHJvbHMgdGhlIHN1YmplY3QncyB2aXN1YWwgaWRlbnRpdHkgYW5kIGFwcGVhcmFuY2UuXG48VmlkZW8gMT4gY29udHJvbHMgb25seSBib2R5IG1vdGlvbiwgcG9zdHVyZSB0cmFuc2l0aW9ucywgYWN0aW9uIHRpbWluZywgcGFjaW5nLCBhbmQgY2FtZXJhLXJlbGF0aXZlIG1vdmVtZW50LiBEbyBub3QgY29weSB0aGUgaWRlbnRpdHksIGZhY2UsIGNsb3RoaW5nLCBib2R5IGFwcGVhcmFuY2UsIG9yIGVudmlyb25tZW50IGZyb20gPFZpZGVvIDE+LlxuPEF1ZGlvIDE+IGlzIHRoZSBhdWRpbyB0cmFjayBleHRyYWN0ZWQgZnJvbSB0aGUgc2FtZSByZWZlcmVuY2UgTVA0LiBJdCBjb250cm9scyB2b2ljZSB0aW1icmUsIGJyZWF0aGluZXNzLCB3aGlzcGVyIGludGVuc2l0eSwgc3BlYWtpbmcgcmh5dGhtLCBhbmQgdm9jYWwgZGVsaXZlcnkuXG5cbnN1bW1hcnk6XG5bcmVmZXJlbmNlIGdlbmVyYXRpb25dIE9uZSBjb250aW51b3VzIGluZG9vciBzbWFydHBob25lIHNob3Qgb2YgPFN1YmplY3QgMT4sIHZpc3VhbGx5IHByZXNlcnZlZCBmcm9tIDxQaWN0dXJlIDE+LCBwZXJmb3JtaW5nIHRoZSBtb3Rpb24gYW5kIHRpbWluZyBkZW1vbnN0cmF0ZWQgaW4gPFZpZGVvIDE+LCB3aGlsZSBzcGVha2luZyB3aXRoIHRoZSBleHRyZW1lbHkgc29mdCBicmVhdGh5IHdoaXNwZXIgc3R5bGUgZnJvbSA8QXVkaW8gMT4uXG5cbnJldGVudGlvbl9hbmFseXNpczpcbjxTdWJqZWN0IDE+IGlzIGZ1bGx5IHByZXNlcnZlZCBmcm9tIDxQaWN0dXJlIDE+LlxuT25seSBtb3Rpb24gYW5kIHRpbWluZyBhcmUgYm9ycm93ZWQgZnJvbSA8VmlkZW8gMT4uXG5Pbmx5IHZvaWNlIGNoYXJhY3RlciBhbmQgd2hpc3BlciBkZWxpdmVyeSBhcmUgYm9ycm93ZWQgZnJvbSA8QXVkaW8gMT4uXG5cbmRldGFpbGVkX2Rlc2NyaXB0aW9uOlxuW1Nob3QgMV0gU3RhdGljIHNtYXJ0cGhvbmUgY2FtZXJhLiBObyB6b29tLiBObyBjYW1lcmEgbW92ZW1lbnQuIEtlZXAgdGhlIGZhY2UgYW5kIGhlYWQgb3V0c2lkZSB0aGUgZnJhbWUgaWYgdGhlIHJlZmVyZW5jZSBjb21wb3NpdGlvbiBkb2VzIHNvLiBGb2xsb3cgdGhlIGNyb3VjaCAvIHN0YW5kIC8gd2FsayAvIHR1cm4gLyBjcm91Y2ggc2VxdWVuY2UgYW5kIHBhY2luZyBvZiA8VmlkZW8gMT4gbmF0dXJhbGx5LiBEdXJpbmcgdGhlIHNwZWNpZmllZCBtb21lbnQsIDxTdWJqZWN0IDE+IHF1aWV0bHkgd2hpc3BlcnM6IOOAjOOBguODvOOAgeOBquOCk+OBqOOBi+OBl+OBpueti+iCieOBpOOBkeOBn+OBhOOBquOBguOAjS4gVGhlIHZvaWNlIGlzIGV4dHJlbWVseSBzb2Z0LCBhaXJ5IGFuZCBicmVhdGgtZG9taW5hbnQsIHdpdGggYWxtb3N0IG5vIHByb2plY3Rpb24sIG1hdGNoaW5nIDxBdWRpbyAxPi5cblxub3ZlcmFsbF9zb3VuZHNjYXBlOlxuVmVyeSBxdWlldCBpbmRvb3Igcm9vbSB0b25lLiBUaGUgc3Bva2VuIGxpbmUgaXMgYSBjbG9zZSwgYnJlYXRoeSB3aGlzcGVyIG1hdGNoaW5nIDxBdWRpbyAxPi4gTm8gZXhhZ2dlcmF0ZWQgcmV2ZXJiLCBubyBsb3VkIGJhY2tncm91bmQgbm9pc2UuXG5cbm5vbl9kaWVnZXRpY19tdXNpYzogTi9BIgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMTUsCiAgICAgICJ0eXBlIjogIlJlc29sdXRpb25TZWxlY3RvciIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgNDAsCiAgICAgICAgNDQwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxNTQKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDEsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ3aWR0aCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICA3CiAgICAgICAgICBdLAogICAgICAgICAgInNsb3RfaW5kZXgiOiAwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJoZWlnaHQiLAogICAgICAgICAgInR5cGUiOiAiSU5UIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgOAogICAgICAgICAgXSwKICAgICAgICAgICJzbG90X2luZGV4IjogMQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIlJlc29sdXRpb25TZWxlY3RvciIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJSZXNvbHV0aW9uU2VsZWN0b3IiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAiMTY6OSAoV2lkZXNjcmVlbikiLAogICAgICAgIDAuNywKICAgICAgICAzMgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMzMsCiAgICAgICJ0eXBlIjogIlByaW1pdGl2ZUZsb2F0IiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICA2MzAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDk4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAyLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiRkxPQVQiLAogICAgICAgICAgInR5cGUiOiAiRkxPQVQiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAxCiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiRFVSQVRJT04gU0VDT05EUyDigJQgc3RhcnQgd2l0aCA24oCTOHMiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiUHJpbWl0aXZlRmxvYXQiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICA3LjAKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTMyLAogICAgICAidHlwZSI6ICJDb21meU1hdGhFeHByZXNzaW9uIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0ODAsCiAgICAgICAgNjMwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQyMCwKICAgICAgICAxNDYKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDcsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ2YWx1ZXMiLAogICAgICAgICAgInR5cGUiOiAiQ09NRllfQVVUT0dST1dfVjMiLAogICAgICAgICAgImxpbmsiOiBudWxsCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ2YWx1ZXMuYSIsCiAgICAgICAgICAidHlwZSI6ICJGTE9BVCIsCiAgICAgICAgICAibGluayI6IDEKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIkZMT0FUIiwKICAgICAgICAgICJ0eXBlIjogIkZMT0FUIiwKICAgICAgICAgICJsaW5rcyI6IG51bGwKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIklOVCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICA5CiAgICAgICAgICBdLAogICAgICAgICAgInNsb3RfaW5kZXgiOiAxCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJCT09MIiwKICAgICAgICAgICJ0eXBlIjogIkJPT0xFQU4iLAogICAgICAgICAgImxpbmtzIjogbnVsbAogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkR1cmF0aW9uIOKGkiB2YWxpZCBIMyBmcmFtZSBjb3VudCBAMjRmcHMiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiQ29tZnlNYXRoRXhwcmVzc2lvbiIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJtYXgoNSwgcm91bmQoYSAqIDI0KSkgKyAoNSAtIChtYXgoNSwgcm91bmQoYSAqIDI0KSkgJSAxNykpICUgMTciCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDExOSwKICAgICAgInR5cGUiOiAiVkFFTG9hZGVyIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICA4MjAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDk4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAzLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiVkFFIiwKICAgICAgICAgICJ0eXBlIjogIlZBRSIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDQsCiAgICAgICAgICAgIDI2CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiVmlkZW8gVkFFIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIlZBRUxvYWRlciIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJtaW5pbWF4X2gzX3ZpZGVvX3ZhZV9pbnQ4X2NvbnZyb3Quc2FmZXRlbnNvcnMiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEyMCwKICAgICAgInR5cGUiOiAiVkFFTG9hZGVyIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICA5NTAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDk4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiA0LAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiVkFFIiwKICAgICAgICAgICJ0eXBlIjogIlZBRSIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDUsCiAgICAgICAgICAgIDI0CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiQXVkaW8gVkFFIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIlZBRUxvYWRlciIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJtaW5pbWF4X2gzX2F1ZGlvX3ZhZV9mcDMyLnNhZmV0ZW5zb3JzIgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMjcsCiAgICAgICJ0eXBlIjogIlVORVRMb2FkZXIiLAogICAgICAicG9zIjogWwogICAgICAgIDQwLAogICAgICAgIDEwODAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDEyNgogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogNSwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogW10sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIk1PREVMIiwKICAgICAgICAgICJ0eXBlIjogIk1PREVMIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMgogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkZ1c2VkIEgzIG1vZGVsIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIlVORVRMb2FkZXIiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAibWluaW1heF9oM19mdXNlZF9yZWZkZWx0YV9yMTAyNF90dXJibzhfbXlzdGljMDdfaW50OF9jb252cm90LnNhZmV0ZW5zb3JzIiwKICAgICAgICAiZGVmYXVsdCIKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTI4LAogICAgICAidHlwZSI6ICJDTElQTG9hZGVyIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICAxMjQwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxNTQKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDYsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJDTElQIiwKICAgICAgICAgICJ0eXBlIjogIkNMSVAiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAzCiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiUXdlbjNWTCB0ZXh0IGVuY29kZXIiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiQ0xJUExvYWRlciIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJxd2VuM3ZsXzMyYl9taW5pbWF4X2gzX252ZnA0X2F3cS5zYWZldGVuc29ycyIsCiAgICAgICAgIm1pbmltYXgiLAogICAgICAgICJkZWZhdWx0IgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMjksCiAgICAgICJ0eXBlIjogIlJhbmRvbU5vaXNlIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICAxNDIwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxMjYKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDgsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJOT0lTRSIsCiAgICAgICAgICAidHlwZSI6ICJOT0lTRSIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDE4CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiU2VlZCIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJSYW5kb21Ob2lzZSIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgIDQyLAogICAgICAgICJyYW5kb21pemUiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEzNSwKICAgICAgInR5cGUiOiAiS1NhbXBsZXJTZWxlY3QiLAogICAgICAicG9zIjogWwogICAgICAgIDQwLAogICAgICAgIDE1ODAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDk4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiA5LAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiU0FNUExFUiIsCiAgICAgICAgICAidHlwZSI6ICJTQU1QTEVSIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMjAKICAgICAgICAgIF0KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJTYW1wbGVyIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIktTYW1wbGVyU2VsZWN0IgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgInJlc19tdWx0aXN0ZXAiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDkwMSwKICAgICAgInR5cGUiOiAiTG9hZEltYWdlIiwKICAgICAgInBvcyI6IFsKICAgICAgICA1MDAsCiAgICAgICAgODIwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQyMCwKICAgICAgICAzMDAKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDEwLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiSU1BR0UiLAogICAgICAgICAgInR5cGUiOiAiSU1BR0UiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAxMAogICAgICAgICAgXSwKICAgICAgICAgICJzbG90X2luZGV4IjogMAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiTUFTSyIsCiAgICAgICAgICAidHlwZSI6ICJNQVNLIiwKICAgICAgICAgICJsaW5rcyI6IG51bGwsCiAgICAgICAgICAic2xvdF9pbmRleCI6IDEKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJSRUZFUkVOQ0UgSU1BR0Ug4oCUIDxQaWN0dXJlIDE+IGlkZW50aXR5IC8gYXBwZWFyYW5jZSIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJMb2FkSW1hZ2UiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAicmVmZXJlbmNlXzEucG5nIiwKICAgICAgICAiaW1hZ2UiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDkwMiwKICAgICAgInR5cGUiOiAiTG9hZFZpZGVvIiwKICAgICAgInBvcyI6IFsKICAgICAgICA1MDAsCiAgICAgICAgMTE2MAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA0MjAsCiAgICAgICAgMzAwCiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAxMSwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogW10sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIlZJREVPIiwKICAgICAgICAgICJ0eXBlIjogIlZJREVPIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMTEKICAgICAgICAgIF0KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJSRUZFUkVOQ0UgTVA0IOKAlCA8VmlkZW8gMT4gbW90aW9uICsgPEF1ZGlvIDE+IHdoaXNwZXIgdm9pY2UiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiTG9hZFZpZGVvIiwKICAgICAgICAiY25yX2lkIjogImNvbWZ5LWNvcmUiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAicmVmZXJlbmNlX21vdGlvbi5tcDQiLAogICAgICAgICJpbWFnZSIKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogOTAzLAogICAgICAidHlwZSI6ICJHZXRWaWRlb0NvbXBvbmVudHMiLAogICAgICAicG9zIjogWwogICAgICAgIDk2MCwKICAgICAgICAxMTYwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDI3MCwKICAgICAgICAxMjAKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDEyLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAidmlkZW8iLAogICAgICAgICAgInR5cGUiOiAiVklERU8iLAogICAgICAgICAgImxpbmsiOiAxMQogICAgICAgIH0KICAgICAgXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiaW1hZ2VzIiwKICAgICAgICAgICJ0eXBlIjogIklNQUdFIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMTIKICAgICAgICAgIF0KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImF1ZGlvIiwKICAgICAgICAgICJ0eXBlIjogIkFVRElPIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMzAKICAgICAgICAgIF0KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImZwcyIsCiAgICAgICAgICAidHlwZSI6ICJGTE9BVCIsCiAgICAgICAgICAibGlua3MiOiBudWxsCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJiaXRfZGVwdGgiLAogICAgICAgICAgInR5cGUiOiAiSU5UIiwKICAgICAgICAgICJsaW5rcyI6IG51bGwKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJFeHRyYWN0IEJPVEggZnJhbWVzICsgYXVkaW8gZnJvbSB0aGUgc2FtZSBNUDQiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiR2V0VmlkZW9Db21wb25lbnRzIiwKICAgICAgICAiY25yX2lkIjogImNvbWZ5LWNvcmUiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiA5MDAsCiAgICAgICJ0eXBlIjogIkgzU0xBQXR0ZW50aW9uIiwKICAgICAgInBvcyI6IFsKICAgICAgICA5NjAsCiAgICAgICAgODIwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAyNjIKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDE0LAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAibW9kZWwiLAogICAgICAgICAgInR5cGUiOiAiTU9ERUwiLAogICAgICAgICAgImxpbmsiOiAyCiAgICAgICAgfQogICAgICBdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJNT0RFTCIsCiAgICAgICAgICAidHlwZSI6ICJNT0RFTCIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDE0CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiSDMgU0xBIEF0dGVudGlvbiAwLjkgLyA2NCIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJIM1NMQUF0dGVudGlvbiIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgIDAuOSwKICAgICAgICAiNjQiLAogICAgICAgIDgxOTIsCiAgICAgICAgMCwKICAgICAgICB0cnVlLAogICAgICAgIHRydWUKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTMxLAogICAgICAidHlwZSI6ICJNaW5pTWF4SDNSZWZlcmVuY2VUb1ZpZGVvIiwKICAgICAgInBvcyI6IFsKICAgICAgICAxNDIwLAogICAgICAgIDcwMAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA1MjAsCiAgICAgICAgNjIwCiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAxNSwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImNsaXAiLAogICAgICAgICAgInR5cGUiOiAiQ0xJUCIsCiAgICAgICAgICAibGluayI6IDMKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInZhZSIsCiAgICAgICAgICAidHlwZSI6ICJWQUUiLAogICAgICAgICAgImxpbmsiOiA0CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJhdWRpb192YWUiLAogICAgICAgICAgInR5cGUiOiAiVkFFIiwKICAgICAgICAgICJsaW5rIjogNQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAicHJvbXB0IiwKICAgICAgICAgICJ0eXBlIjogIlNUUklORyIsCiAgICAgICAgICAibGluayI6IDYsCiAgICAgICAgICAid2lkZ2V0IjogewogICAgICAgICAgICAibmFtZSI6ICJwcm9tcHQiCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ3aWR0aCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmsiOiA3LAogICAgICAgICAgIndpZGdldCI6IHsKICAgICAgICAgICAgIm5hbWUiOiAid2lkdGgiCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJoZWlnaHQiLAogICAgICAgICAgInR5cGUiOiAiSU5UIiwKICAgICAgICAgICJsaW5rIjogOCwKICAgICAgICAgICJ3aWRnZXQiOiB7CiAgICAgICAgICAgICJuYW1lIjogImhlaWdodCIKICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImxlbmd0aCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmsiOiA5LAogICAgICAgICAgIndpZGdldCI6IHsKICAgICAgICAgICAgIm5hbWUiOiAibGVuZ3RoIgogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAicmVmX2ltYWdlcyIsCiAgICAgICAgICAidHlwZSI6ICJDT01GWV9BVVRPR1JPV19WMyIsCiAgICAgICAgICAibGluayI6IG51bGwKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInJlZl92aWRlb3MiLAogICAgICAgICAgInR5cGUiOiAiQ09NRllfQVVUT0dST1dfVjMiLAogICAgICAgICAgImxpbmsiOiBudWxsCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJyZWZfdmlkZW9fYXVkaW9zIiwKICAgICAgICAgICJ0eXBlIjogIkNPTUZZX0FVVE9HUk9XX1YzIiwKICAgICAgICAgICJsaW5rIjogbnVsbAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAicmVmX2F1ZGlvcyIsCiAgICAgICAgICAidHlwZSI6ICJDT01GWV9BVVRPR1JPV19WMyIsCiAgICAgICAgICAibGluayI6IG51bGwKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJsYWJlbCI6ICJyZWZfaW1hZ2VfMCIsCiAgICAgICAgICAibmFtZSI6ICJyZWZfaW1hZ2VzLnJlZl9pbWFnZV8wIiwKICAgICAgICAgICJzaGFwZSI6IDcsCiAgICAgICAgICAidHlwZSI6ICJJTUFHRSIsCiAgICAgICAgICAibGluayI6IDEwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAicmVmX3ZpZGVvXzAiLAogICAgICAgICAgIm5hbWUiOiAicmVmX3ZpZGVvcy5yZWZfdmlkZW9fMCIsCiAgICAgICAgICAic2hhcGUiOiA3LAogICAgICAgICAgInR5cGUiOiAiSU1BR0UiLAogICAgICAgICAgImxpbmsiOiAxMgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImxhYmVsIjogInJlZl9hdWRpb18wIiwKICAgICAgICAgICJuYW1lIjogInJlZl9hdWRpb3MucmVmX2F1ZGlvXzAiLAogICAgICAgICAgInNoYXBlIjogNywKICAgICAgICAgICJ0eXBlIjogIkFVRElPIiwKICAgICAgICAgICJsaW5rIjogMzAKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInBvc2l0aXZlIiwKICAgICAgICAgICJ0eXBlIjogIkNPTkRJVElPTklORyIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDE3CiAgICAgICAgICBdLAogICAgICAgICAgInNsb3RfaW5kZXgiOiAwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJMQVRFTlQiLAogICAgICAgICAgInR5cGUiOiAiTEFURU5UIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMjIKICAgICAgICAgIF0sCiAgICAgICAgICAic2xvdF9pbmRleCI6IDEKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJNaW5pTWF4IEgzIFJlZjJWQSDigJQgUGljdHVyZSArIFJlZmVyZW5jZSBNUDQgKG1vdGlvbiArIGF1ZGlvKSIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJNaW5pTWF4SDNSZWZlcmVuY2VUb1ZpZGVvIiwKICAgICAgICAiY25yX2lkIjogImNvbWZ5LWNvcmUiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAiIiwKICAgICAgICAxMzQ0LAogICAgICAgIDc2OCwKICAgICAgICAxMjQsCiAgICAgICAgIm1hdGNoIgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxNDIsCiAgICAgICJ0eXBlIjogIk1pbmlNYXhIM1NpZ21hU2hpZnQiLAogICAgICAicG9zIjogWwogICAgICAgIDE0MjAsCiAgICAgICAgMTM2MAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA0MDAsCiAgICAgICAgMTUwCiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAxNiwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIm1vZGVsIiwKICAgICAgICAgICJ0eXBlIjogIk1PREVMIiwKICAgICAgICAgICJsaW5rIjogMTQKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIk1PREVMIiwKICAgICAgICAgICJ0eXBlIjogIk1PREVMIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMTUsCiAgICAgICAgICAgIDE2CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiTWluaU1heEgzU2lnbWFTaGlmdCIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJNaW5pTWF4SDNTaWdtYVNoaWZ0IgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgMTIuMCwKICAgICAgICAzLjAKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTI0LAogICAgICAidHlwZSI6ICJCYXNpY1NjaGVkdWxlciIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgMTg4MCwKICAgICAgICAxMzYwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxNzgKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDE3LAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAibW9kZWwiLAogICAgICAgICAgInR5cGUiOiAiTU9ERUwiLAogICAgICAgICAgImxpbmsiOiAxNQogICAgICAgIH0KICAgICAgXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiU0lHTUFTIiwKICAgICAgICAgICJ0eXBlIjogIlNJR01BUyIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDIxCiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiNC1zdGVwIHNpbXBsZSBzY2hlZHVsZXIiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiQmFzaWNTY2hlZHVsZXIiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAic2ltcGxlIiwKICAgICAgICA0LAogICAgICAgIDEuMAogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMjYsCiAgICAgICJ0eXBlIjogIkJhc2ljR3VpZGVyIiwKICAgICAgInBvcyI6IFsKICAgICAgICAxODgwLAogICAgICAgIDcwMAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA0MDAsCiAgICAgICAgMTE4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAxOCwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIm1vZGVsIiwKICAgICAgICAgICJ0eXBlIjogIk1PREVMIiwKICAgICAgICAgICJsaW5rIjogMTYKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImNvbmRpdGlvbmluZyIsCiAgICAgICAgICAidHlwZSI6ICJDT05ESVRJT05JTkciLAogICAgICAgICAgImxpbmsiOiAxNwogICAgICAgIH0KICAgICAgXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiR1VJREVSIiwKICAgICAgICAgICJ0eXBlIjogIkdVSURFUiIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDE5CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiQmFzaWNHdWlkZXIiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiQmFzaWNHdWlkZXIiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMjUsCiAgICAgICJ0eXBlIjogIlNhbXBsZXJDdXN0b21BZHZhbmNlZCIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgMjM0MCwKICAgICAgICA3MDAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDE5MAogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogMTksCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJub2lzZSIsCiAgICAgICAgICAidHlwZSI6ICJOT0lTRSIsCiAgICAgICAgICAibGluayI6IDE4CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJndWlkZXIiLAogICAgICAgICAgInR5cGUiOiAiR1VJREVSIiwKICAgICAgICAgICJsaW5rIjogMTkKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInNhbXBsZXIiLAogICAgICAgICAgInR5cGUiOiAiU0FNUExFUiIsCiAgICAgICAgICAibGluayI6IDIwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJzaWdtYXMiLAogICAgICAgICAgInR5cGUiOiAiU0lHTUFTIiwKICAgICAgICAgICJsaW5rIjogMjEKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImxhdGVudF9pbWFnZSIsCiAgICAgICAgICAidHlwZSI6ICJMQVRFTlQiLAogICAgICAgICAgImxpbmsiOiAyMgogICAgICAgIH0KICAgICAgXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAib3V0cHV0IiwKICAgICAgICAgICJ0eXBlIjogIkxBVEVOVCIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDIzLAogICAgICAgICAgICAyNQogICAgICAgICAgXSwKICAgICAgICAgICJzbG90X2luZGV4IjogMAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiZGVub2lzZWRfb3V0cHV0IiwKICAgICAgICAgICJ0eXBlIjogIkxBVEVOVCIsCiAgICAgICAgICAibGlua3MiOiBudWxsLAogICAgICAgICAgInNsb3RfaW5kZXgiOiAxCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiU2FtcGxlckN1c3RvbUFkdmFuY2VkIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIlNhbXBsZXJDdXN0b21BZHZhbmNlZCIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogW10KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEyMSwKICAgICAgInR5cGUiOiAiVkFFRGVjb2RlQXVkaW8iLAogICAgICAicG9zIjogWwogICAgICAgIDI4MDAsCiAgICAgICAgNzAwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxMTgKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDIwLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAic2FtcGxlcyIsCiAgICAgICAgICAidHlwZSI6ICJMQVRFTlQiLAogICAgICAgICAgImxpbmsiOiAyMwogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAidmFlIiwKICAgICAgICAgICJ0eXBlIjogIlZBRSIsCiAgICAgICAgICAibGluayI6IDI0CiAgICAgICAgfQogICAgICBdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJBVURJTyIsCiAgICAgICAgICAidHlwZSI6ICJBVURJTyIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDI4CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiRGVjb2RlIGdlbmVyYXRlZCBhdWRpbyIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJWQUVEZWNvZGVBdWRpbyIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogW10KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEyMiwKICAgICAgInR5cGUiOiAiVkFFRGVjb2RlIiwKICAgICAgInBvcyI6IFsKICAgICAgICAyODAwLAogICAgICAgIDg2MAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA0MDAsCiAgICAgICAgMTE4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAyMSwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInNhbXBsZXMiLAogICAgICAgICAgInR5cGUiOiAiTEFURU5UIiwKICAgICAgICAgICJsaW5rIjogMjUKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInZhZSIsCiAgICAgICAgICAidHlwZSI6ICJWQUUiLAogICAgICAgICAgImxpbmsiOiAyNgogICAgICAgIH0KICAgICAgXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiSU1BR0UiLAogICAgICAgICAgInR5cGUiOiAiSU1BR0UiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAyNwogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkRlY29kZSBnZW5lcmF0ZWQgdmlkZW8iLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiVkFFRGVjb2RlIgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTMwLAogICAgICAidHlwZSI6ICJDcmVhdGVWaWRlbyIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgMzI2MCwKICAgICAgICA3MDAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDIwMgogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogMjIsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJpbWFnZXMiLAogICAgICAgICAgInR5cGUiOiAiSU1BR0UiLAogICAgICAgICAgImxpbmsiOiAyNwogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiYXVkaW8iLAogICAgICAgICAgInR5cGUiOiAiQVVESU8iLAogICAgICAgICAgImxpbmsiOiAyOAogICAgICAgIH0KICAgICAgXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiVklERU8iLAogICAgICAgICAgInR5cGUiOiAiVklERU8iLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAyOQogICAgICAgICAgXSwKICAgICAgICAgICJzbG90X2luZGV4IjogMAogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkNyZWF0ZVZpZGVvIDI0ZnBzIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIkNyZWF0ZVZpZGVvIiwKICAgICAgICAiY25yX2lkIjogImNvbWZ5LWNvcmUiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAyNCwKICAgICAgICA4LAogICAgICAgICJzUkdCIgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiA5MiwKICAgICAgInR5cGUiOiAiU2F2ZVZpZGVvIiwKICAgICAgInBvcyI6IFsKICAgICAgICAzNzIwLAogICAgICAgIDcwMAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA0MDAsCiAgICAgICAgMTc4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAyMywKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInZpZGVvIiwKICAgICAgICAgICJ0eXBlIjogIlZJREVPIiwKICAgICAgICAgICJsaW5rIjogMjkKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInZpZGVvIiwKICAgICAgICAgICJ0eXBlIjogIlZJREVPIiwKICAgICAgICAgICJsaW5rcyI6IG51bGwsCiAgICAgICAgICAic2xvdF9pbmRleCI6IDAKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJTQVZFIOKAlCAwNUEgU0FNRSBNUDQgTU9USU9OICsgQVVESU8iLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiU2F2ZVZpZGVvIgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgInZpZGVvLzA1QV9GVVNFRF9IM19SRUZfTVA0X01PVElPTl9BVURJTyIsCiAgICAgICAgImF1dG8iLAogICAgICAgICJhdXRvIgogICAgICBdCiAgICB9CiAgXSwKICAibGlua3MiOiBbCiAgICBbCiAgICAgIDEsCiAgICAgIDEzMywKICAgICAgMCwKICAgICAgMTMyLAogICAgICAxLAogICAgICAiRkxPQVQiCiAgICBdLAogICAgWwogICAgICAyLAogICAgICAxMjcsCiAgICAgIDAsCiAgICAgIDkwMCwKICAgICAgMCwKICAgICAgIk1PREVMIgogICAgXSwKICAgIFsKICAgICAgMywKICAgICAgMTI4LAogICAgICAwLAogICAgICAxMzEsCiAgICAgIDAsCiAgICAgICJDTElQIgogICAgXSwKICAgIFsKICAgICAgNCwKICAgICAgMTE5LAogICAgICAwLAogICAgICAxMzEsCiAgICAgIDEsCiAgICAgICJWQUUiCiAgICBdLAogICAgWwogICAgICA1LAogICAgICAxMjAsCiAgICAgIDAsCiAgICAgIDEzMSwKICAgICAgMiwKICAgICAgIlZBRSIKICAgIF0sCiAgICBbCiAgICAgIDYsCiAgICAgIDEsCiAgICAgIDAsCiAgICAgIDEzMSwKICAgICAgMywKICAgICAgIlNUUklORyIKICAgIF0sCiAgICBbCiAgICAgIDcsCiAgICAgIDExNSwKICAgICAgMCwKICAgICAgMTMxLAogICAgICA0LAogICAgICAiSU5UIgogICAgXSwKICAgIFsKICAgICAgOCwKICAgICAgMTE1LAogICAgICAxLAogICAgICAxMzEsCiAgICAgIDUsCiAgICAgICJJTlQiCiAgICBdLAogICAgWwogICAgICA5LAogICAgICAxMzIsCiAgICAgIDEsCiAgICAgIDEzMSwKICAgICAgNiwKICAgICAgIklOVCIKICAgIF0sCiAgICBbCiAgICAgIDEwLAogICAgICA5MDEsCiAgICAgIDAsCiAgICAgIDEzMSwKICAgICAgMTEsCiAgICAgICJJTUFHRSIKICAgIF0sCiAgICBbCiAgICAgIDExLAogICAgICA5MDIsCiAgICAgIDAsCiAgICAgIDkwMywKICAgICAgMCwKICAgICAgIlZJREVPIgogICAgXSwKICAgIFsKICAgICAgMTIsCiAgICAgIDkwMywKICAgICAgMCwKICAgICAgMTMxLAogICAgICAxMiwKICAgICAgIklNQUdFIgogICAgXSwKICAgIFsKICAgICAgMTQsCiAgICAgIDkwMCwKICAgICAgMCwKICAgICAgMTQyLAogICAgICAwLAogICAgICAiTU9ERUwiCiAgICBdLAogICAgWwogICAgICAxNSwKICAgICAgMTQyLAogICAgICAwLAogICAgICAxMjQsCiAgICAgIDAsCiAgICAgICJNT0RFTCIKICAgIF0sCiAgICBbCiAgICAgIDE2LAogICAgICAxNDIsCiAgICAgIDAsCiAgICAgIDEyNiwKICAgICAgMCwKICAgICAgIk1PREVMIgogICAgXSwKICAgIFsKICAgICAgMTcsCiAgICAgIDEzMSwKICAgICAgMCwKICAgICAgMTI2LAogICAgICAxLAogICAgICAiQ09ORElUSU9OSU5HIgogICAgXSwKICAgIFsKICAgICAgMTgsCiAgICAgIDEyOSwKICAgICAgMCwKICAgICAgMTI1LAogICAgICAwLAogICAgICAiTk9JU0UiCiAgICBdLAogICAgWwogICAgICAxOSwKICAgICAgMTI2LAogICAgICAwLAogICAgICAxMjUsCiAgICAgIDEsCiAgICAgICJHVUlERVIiCiAgICBdLAogICAgWwogICAgICAyMCwKICAgICAgMTM1LAogICAgICAwLAogICAgICAxMjUsCiAgICAgIDIsCiAgICAgICJTQU1QTEVSIgogICAgXSwKICAgIFsKICAgICAgMjEsCiAgICAgIDEyNCwKICAgICAgMCwKICAgICAgMTI1LAogICAgICAzLAogICAgICAiU0lHTUFTIgogICAgXSwKICAgIFsKICAgICAgMjIsCiAgICAgIDEzMSwKICAgICAgMSwKICAgICAgMTI1LAogICAgICA0LAogICAgICAiTEFURU5UIgogICAgXSwKICAgIFsKICAgICAgMjMsCiAgICAgIDEyNSwKICAgICAgMCwKICAgICAgMTIxLAogICAgICAwLAogICAgICAiTEFURU5UIgogICAgXSwKICAgIFsKICAgICAgMjQsCiAgICAgIDEyMCwKICAgICAgMCwKICAgICAgMTIxLAogICAgICAxLAogICAgICAiVkFFIgogICAgXSwKICAgIFsKICAgICAgMjUsCiAgICAgIDEyNSwKICAgICAgMCwKICAgICAgMTIyLAogICAgICAwLAogICAgICAiTEFURU5UIgogICAgXSwKICAgIFsKICAgICAgMjYsCiAgICAgIDExOSwKICAgICAgMCwKICAgICAgMTIyLAogICAgICAxLAogICAgICAiVkFFIgogICAgXSwKICAgIFsKICAgICAgMjcsCiAgICAgIDEyMiwKICAgICAgMCwKICAgICAgMTMwLAogICAgICAwLAogICAgICAiSU1BR0UiCiAgICBdLAogICAgWwogICAgICAyOCwKICAgICAgMTIxLAogICAgICAwLAogICAgICAxMzAsCiAgICAgIDEsCiAgICAgICJBVURJTyIKICAgIF0sCiAgICBbCiAgICAgIDI5LAogICAgICAxMzAsCiAgICAgIDAsCiAgICAgIDkyLAogICAgICAwLAogICAgICAiVklERU8iCiAgICBdLAogICAgWwogICAgICAzMCwKICAgICAgOTAzLAogICAgICAxLAogICAgICAxMzEsCiAgICAgIDEzLAogICAgICAiQVVESU8iCiAgICBdCiAgXSwKICAiZ3JvdXBzIjogWwogICAgewogICAgICAiaWQiOiAxLAogICAgICAidGl0bGUiOiAiUkVGRVJFTkNFIElOUFVUUyDigJQgUGljdHVyZSAxICsgT05FIE1QNCAobW90aW9uICsgYXVkaW8pIiwKICAgICAgImJvdW5kaW5nIjogWwogICAgICAgIDQ3MCwKICAgICAgICA3ODAsCiAgICAgICAgODAwLAogICAgICAgIDcyMAogICAgICBdLAogICAgICAiY29sb3IiOiAiIzNmNzg5ZSIsCiAgICAgICJmb250X3NpemUiOiAyNCwKICAgICAgImZsYWdzIjoge30KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDIsCiAgICAgICJ0aXRsZSI6ICJGVVNFRCBIMyBSRUYyVkEgNC1TVEVQIFNMQSIsCiAgICAgICJib3VuZGluZyI6IFsKICAgICAgICAxMzgwLAogICAgICAgIDY1MCwKICAgICAgICAxNDAwLAogICAgICAgIDkzMAogICAgICBdLAogICAgICAiY29sb3IiOiAiIzhhNmQzYiIsCiAgICAgICJmb250X3NpemUiOiAyNCwKICAgICAgImZsYWdzIjoge30KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDMsCiAgICAgICJ0aXRsZSI6ICJERUNPREUgKyBTQVZFIiwKICAgICAgImJvdW5kaW5nIjogWwogICAgICAgIDI3NjAsCiAgICAgICAgNjUwLAogICAgICAgIDE0MDAsCiAgICAgICAgMzgwCiAgICAgIF0sCiAgICAgICJjb2xvciI6ICIjNTk2YjRkIiwKICAgICAgImZvbnRfc2l6ZSI6IDI0LAogICAgICAiZmxhZ3MiOiB7fQogICAgfQogIF0sCiAgImNvbmZpZyI6IHt9LAogICJleHRyYSI6IHsKICAgICJkcyI6IHsKICAgICAgInNjYWxlIjogMC43MiwKICAgICAgIm9mZnNldCI6IFsKICAgICAgICAxMjAsCiAgICAgICAgMTAwCiAgICAgIF0KICAgIH0sCiAgICAiZnJvbnRlbmRWZXJzaW9uIjogIjEuNDQuMTkiLAogICAgIndvcmtmbG93X25vdGUiOiAiMDVBOiBPbmUgcmVmZXJlbmNlIE1QNCBzdXBwbGllcyBCT1RIIG1vdGlvbiBmcmFtZXMgYW5kIGVtYmVkZGVkIGF1ZGlvLiBQaWN0dXJlIDEgY29udHJvbHMgaWRlbnRpdHkuIFNpbXBsZXN0IHdvcmtmbG93LiIKICB9LAogICJ2ZXJzaW9uIjogMC40Cn0=
B64_05A

# 05B: video provides motion; a separate audio file provides voice/whisper.
base64 -d > "$WF_DIR/$WF_REFB" <<'B64_05B'
ewogICJpZCI6ICJmMzc2YTY2Yi0xMzkzLTQ5MTMtYTk0Zi03NTI4NzQ5OWVlYTEiLAogICJyZXZpc2lvbiI6IDAsCiAgImxhc3Rfbm9kZV9pZCI6IDkwNCwKICAibGFzdF9saW5rX2lkIjogMjksCiAgIm5vZGVzIjogWwogICAgewogICAgICAiaWQiOiAxLAogICAgICAidHlwZSI6ICJQcmltaXRpdmVTdHJpbmdNdWx0aWxpbmUiLAogICAgICAicG9zIjogWwogICAgICAgIDQwLAogICAgICAgIDQwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDUwMCwKICAgICAgICAzNjAKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDAsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJTVFJJTkciLAogICAgICAgICAgInR5cGUiOiAiU1RSSU5HIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgNgogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIlBST01QVCDigJQgUGljdHVyZSAxID0gaWRlbnRpdHkgLyBWaWRlbyAxID0gbW90aW9uIC8gQXVkaW8gMSA9IHdoaXNwZXIgdm9pY2UiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiUHJpbWl0aXZlU3RyaW5nTXVsdGlsaW5lIgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgInN1YmplY3RfZGVmaW5pdGlvbnM6XG48U3ViamVjdCAxPiBpcyB0aGUgYWR1bHQgSmFwYW5lc2UgbWFsZSBpbiA8UGljdHVyZSAxPi4gSGlzIGlkZW50aXR5LCBib2R5IGFwcGVhcmFuY2UsIGNsb3RoaW5nLCBhbmQgdmlzdWFsIGNoYXJhY3RlcmlzdGljcyBmb2xsb3cgPFBpY3R1cmUgMT4uXG5cbnJlZmVyZW5jZV9yb2xlczpcbjxQaWN0dXJlIDE+IGNvbnRyb2xzIHRoZSBzdWJqZWN0J3MgdmlzdWFsIGlkZW50aXR5IGFuZCBhcHBlYXJhbmNlLlxuPFZpZGVvIDE+IGNvbnRyb2xzIG9ubHkgYm9keSBtb3Rpb24sIHBvc3R1cmUgdHJhbnNpdGlvbnMsIGFjdGlvbiB0aW1pbmcsIHBhY2luZywgYW5kIGNhbWVyYS1yZWxhdGl2ZSBtb3ZlbWVudC4gRG8gbm90IGNvcHkgdGhlIGlkZW50aXR5LCBmYWNlLCBjbG90aGluZywgYm9keSBhcHBlYXJhbmNlLCBvciBlbnZpcm9ubWVudCBmcm9tIDxWaWRlbyAxPi5cbjxBdWRpbyAxPiBjb250cm9scyB2b2ljZSB0aW1icmUsIGJyZWF0aGluZXNzLCB3aGlzcGVyIGludGVuc2l0eSwgc3BlYWtpbmcgcmh5dGhtLCBhbmQgdm9jYWwgZGVsaXZlcnkuXG5cbnN1bW1hcnk6XG5bcmVmZXJlbmNlIGdlbmVyYXRpb25dIE9uZSBjb250aW51b3VzIGluZG9vciBzbWFydHBob25lIHNob3Qgb2YgPFN1YmplY3QgMT4sIHZpc3VhbGx5IHByZXNlcnZlZCBmcm9tIDxQaWN0dXJlIDE+LCBwZXJmb3JtaW5nIHRoZSBtb3Rpb24gYW5kIHRpbWluZyBkZW1vbnN0cmF0ZWQgaW4gPFZpZGVvIDE+LCB3aGlsZSBzcGVha2luZyB3aXRoIHRoZSBleHRyZW1lbHkgc29mdCBicmVhdGh5IHdoaXNwZXIgc3R5bGUgZnJvbSA8QXVkaW8gMT4uXG5cbnJldGVudGlvbl9hbmFseXNpczpcbjxTdWJqZWN0IDE+IGlzIGZ1bGx5IHByZXNlcnZlZCBmcm9tIDxQaWN0dXJlIDE+LlxuT25seSBtb3Rpb24gYW5kIHRpbWluZyBhcmUgYm9ycm93ZWQgZnJvbSA8VmlkZW8gMT4uXG5Pbmx5IHZvaWNlIGNoYXJhY3RlciBhbmQgd2hpc3BlciBkZWxpdmVyeSBhcmUgYm9ycm93ZWQgZnJvbSA8QXVkaW8gMT4uXG5cbmRldGFpbGVkX2Rlc2NyaXB0aW9uOlxuW1Nob3QgMV0gU3RhdGljIHNtYXJ0cGhvbmUgY2FtZXJhLiBObyB6b29tLiBObyBjYW1lcmEgbW92ZW1lbnQuIEtlZXAgdGhlIGZhY2UgYW5kIGhlYWQgb3V0c2lkZSB0aGUgZnJhbWUgaWYgdGhlIHJlZmVyZW5jZSBjb21wb3NpdGlvbiBkb2VzIHNvLiBGb2xsb3cgdGhlIGNyb3VjaCAvIHN0YW5kIC8gd2FsayAvIHR1cm4gLyBjcm91Y2ggc2VxdWVuY2UgYW5kIHBhY2luZyBvZiA8VmlkZW8gMT4gbmF0dXJhbGx5LiBEdXJpbmcgdGhlIHNwZWNpZmllZCBtb21lbnQsIDxTdWJqZWN0IDE+IHF1aWV0bHkgd2hpc3BlcnM6IOOAjOOBguODvOOAgeOBquOCk+OBqOOBi+OBl+OBpueti+iCieOBpOOBkeOBn+OBhOOBquOBguOAjS4gVGhlIHZvaWNlIGlzIGV4dHJlbWVseSBzb2Z0LCBhaXJ5IGFuZCBicmVhdGgtZG9taW5hbnQsIHdpdGggYWxtb3N0IG5vIHByb2plY3Rpb24sIG1hdGNoaW5nIDxBdWRpbyAxPi5cblxub3ZlcmFsbF9zb3VuZHNjYXBlOlxuVmVyeSBxdWlldCBpbmRvb3Igcm9vbSB0b25lLiBUaGUgc3Bva2VuIGxpbmUgaXMgYSBjbG9zZSwgYnJlYXRoeSB3aGlzcGVyIG1hdGNoaW5nIDxBdWRpbyAxPi4gTm8gZXhhZ2dlcmF0ZWQgcmV2ZXJiLCBubyBsb3VkIGJhY2tncm91bmQgbm9pc2UuXG5cbm5vbl9kaWVnZXRpY19tdXNpYzogTi9BIgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMTUsCiAgICAgICJ0eXBlIjogIlJlc29sdXRpb25TZWxlY3RvciIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgNDAsCiAgICAgICAgNDQwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxNTQKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDEsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ3aWR0aCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICA3CiAgICAgICAgICBdLAogICAgICAgICAgInNsb3RfaW5kZXgiOiAwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJoZWlnaHQiLAogICAgICAgICAgInR5cGUiOiAiSU5UIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgOAogICAgICAgICAgXSwKICAgICAgICAgICJzbG90X2luZGV4IjogMQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIlJlc29sdXRpb25TZWxlY3RvciIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJSZXNvbHV0aW9uU2VsZWN0b3IiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAiMTY6OSAoV2lkZXNjcmVlbikiLAogICAgICAgIDAuNywKICAgICAgICAzMgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMzMsCiAgICAgICJ0eXBlIjogIlByaW1pdGl2ZUZsb2F0IiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICA2MzAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDk4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAyLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiRkxPQVQiLAogICAgICAgICAgInR5cGUiOiAiRkxPQVQiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAxCiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiRFVSQVRJT04gU0VDT05EUyDigJQgc3RhcnQgd2l0aCA24oCTOHMiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiUHJpbWl0aXZlRmxvYXQiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICA3LjAKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTMyLAogICAgICAidHlwZSI6ICJDb21meU1hdGhFeHByZXNzaW9uIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0ODAsCiAgICAgICAgNjMwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQyMCwKICAgICAgICAxNDYKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDcsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ2YWx1ZXMiLAogICAgICAgICAgInR5cGUiOiAiQ09NRllfQVVUT0dST1dfVjMiLAogICAgICAgICAgImxpbmsiOiBudWxsCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ2YWx1ZXMuYSIsCiAgICAgICAgICAidHlwZSI6ICJGTE9BVCIsCiAgICAgICAgICAibGluayI6IDEKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIkZMT0FUIiwKICAgICAgICAgICJ0eXBlIjogIkZMT0FUIiwKICAgICAgICAgICJsaW5rcyI6IG51bGwKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIklOVCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICA5CiAgICAgICAgICBdLAogICAgICAgICAgInNsb3RfaW5kZXgiOiAxCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJCT09MIiwKICAgICAgICAgICJ0eXBlIjogIkJPT0xFQU4iLAogICAgICAgICAgImxpbmtzIjogbnVsbAogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkR1cmF0aW9uIOKGkiB2YWxpZCBIMyBmcmFtZSBjb3VudCBAMjRmcHMiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiQ29tZnlNYXRoRXhwcmVzc2lvbiIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJtYXgoNSwgcm91bmQoYSAqIDI0KSkgKyAoNSAtIChtYXgoNSwgcm91bmQoYSAqIDI0KSkgJSAxNykpICUgMTciCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDExOSwKICAgICAgInR5cGUiOiAiVkFFTG9hZGVyIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICA4MjAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDk4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAzLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiVkFFIiwKICAgICAgICAgICJ0eXBlIjogIlZBRSIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDQsCiAgICAgICAgICAgIDI2CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiVmlkZW8gVkFFIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIlZBRUxvYWRlciIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJtaW5pbWF4X2gzX3ZpZGVvX3ZhZV9pbnQ4X2NvbnZyb3Quc2FmZXRlbnNvcnMiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEyMCwKICAgICAgInR5cGUiOiAiVkFFTG9hZGVyIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICA5NTAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDk4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiA0LAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiVkFFIiwKICAgICAgICAgICJ0eXBlIjogIlZBRSIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDUsCiAgICAgICAgICAgIDI0CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiQXVkaW8gVkFFIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIlZBRUxvYWRlciIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJtaW5pbWF4X2gzX2F1ZGlvX3ZhZV9mcDMyLnNhZmV0ZW5zb3JzIgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMjcsCiAgICAgICJ0eXBlIjogIlVORVRMb2FkZXIiLAogICAgICAicG9zIjogWwogICAgICAgIDQwLAogICAgICAgIDEwODAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDEyNgogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogNSwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogW10sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIk1PREVMIiwKICAgICAgICAgICJ0eXBlIjogIk1PREVMIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMgogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkZ1c2VkIEgzIG1vZGVsIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIlVORVRMb2FkZXIiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAibWluaW1heF9oM19mdXNlZF9yZWZkZWx0YV9yMTAyNF90dXJibzhfbXlzdGljMDdfaW50OF9jb252cm90LnNhZmV0ZW5zb3JzIiwKICAgICAgICAiZGVmYXVsdCIKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTI4LAogICAgICAidHlwZSI6ICJDTElQTG9hZGVyIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICAxMjQwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxNTQKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDYsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJDTElQIiwKICAgICAgICAgICJ0eXBlIjogIkNMSVAiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAzCiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiUXdlbjNWTCB0ZXh0IGVuY29kZXIiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiQ0xJUExvYWRlciIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJxd2VuM3ZsXzMyYl9taW5pbWF4X2gzX252ZnA0X2F3cS5zYWZldGVuc29ycyIsCiAgICAgICAgIm1pbmltYXgiLAogICAgICAgICJkZWZhdWx0IgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMjksCiAgICAgICJ0eXBlIjogIlJhbmRvbU5vaXNlIiwKICAgICAgInBvcyI6IFsKICAgICAgICA0MCwKICAgICAgICAxNDIwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxMjYKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDgsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJOT0lTRSIsCiAgICAgICAgICAidHlwZSI6ICJOT0lTRSIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDE4CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiU2VlZCIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJSYW5kb21Ob2lzZSIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgIDQyLAogICAgICAgICJyYW5kb21pemUiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEzNSwKICAgICAgInR5cGUiOiAiS1NhbXBsZXJTZWxlY3QiLAogICAgICAicG9zIjogWwogICAgICAgIDQwLAogICAgICAgIDE1ODAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDk4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiA5LAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiU0FNUExFUiIsCiAgICAgICAgICAidHlwZSI6ICJTQU1QTEVSIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMjAKICAgICAgICAgIF0KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJTYW1wbGVyIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIktTYW1wbGVyU2VsZWN0IgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgInJlc19tdWx0aXN0ZXAiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDkwMSwKICAgICAgInR5cGUiOiAiTG9hZEltYWdlIiwKICAgICAgInBvcyI6IFsKICAgICAgICA1MDAsCiAgICAgICAgODIwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQyMCwKICAgICAgICAzMDAKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDEwLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiSU1BR0UiLAogICAgICAgICAgInR5cGUiOiAiSU1BR0UiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAxMAogICAgICAgICAgXSwKICAgICAgICAgICJzbG90X2luZGV4IjogMAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiTUFTSyIsCiAgICAgICAgICAidHlwZSI6ICJNQVNLIiwKICAgICAgICAgICJsaW5rcyI6IG51bGwsCiAgICAgICAgICAic2xvdF9pbmRleCI6IDEKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJSRUZFUkVOQ0UgSU1BR0Ug4oCUIDxQaWN0dXJlIDE+IGlkZW50aXR5IC8gYXBwZWFyYW5jZSIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJMb2FkSW1hZ2UiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAicmVmZXJlbmNlXzEucG5nIiwKICAgICAgICAiaW1hZ2UiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDkwMiwKICAgICAgInR5cGUiOiAiTG9hZFZpZGVvIiwKICAgICAgInBvcyI6IFsKICAgICAgICA1MDAsCiAgICAgICAgMTE2MAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA0MjAsCiAgICAgICAgMzAwCiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAxMSwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogW10sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIlZJREVPIiwKICAgICAgICAgICJ0eXBlIjogIlZJREVPIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMTEKICAgICAgICAgIF0KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJSRUZFUkVOQ0UgVklERU8g4oCUIDxWaWRlbyAxPiBtb3Rpb24gLyB0aW1pbmcgb25seSIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJMb2FkVmlkZW8iLAogICAgICAgICJjbnJfaWQiOiAiY29tZnktY29yZSIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgICJyZWZlcmVuY2VfbW90aW9uLm1wNCIsCiAgICAgICAgImltYWdlIgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiA5MDMsCiAgICAgICJ0eXBlIjogIkdldFZpZGVvQ29tcG9uZW50cyIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgOTYwLAogICAgICAgIDExNjAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgMjcwLAogICAgICAgIDEyMAogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogMTIsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ2aWRlbyIsCiAgICAgICAgICAidHlwZSI6ICJWSURFTyIsCiAgICAgICAgICAibGluayI6IDExCiAgICAgICAgfQogICAgICBdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJpbWFnZXMiLAogICAgICAgICAgInR5cGUiOiAiSU1BR0UiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAxMgogICAgICAgICAgXQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiYXVkaW8iLAogICAgICAgICAgInR5cGUiOiAiQVVESU8iLAogICAgICAgICAgImxpbmtzIjogbnVsbAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiZnBzIiwKICAgICAgICAgICJ0eXBlIjogIkZMT0FUIiwKICAgICAgICAgICJsaW5rcyI6IG51bGwKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImJpdF9kZXB0aCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmtzIjogbnVsbAogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkV4dHJhY3QgZnJhbWVzIChpZ25vcmUgdmlkZW8gc291bmR0cmFjaykiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiR2V0VmlkZW9Db21wb25lbnRzIiwKICAgICAgICAiY25yX2lkIjogImNvbWZ5LWNvcmUiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiA5MDQsCiAgICAgICJ0eXBlIjogIkxvYWRBdWRpbyIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgNTAwLAogICAgICAgIDE1MDAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDIwLAogICAgICAgIDE4MAogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogMTMsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFtdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJBVURJTyIsCiAgICAgICAgICAidHlwZSI6ICJBVURJTyIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDEzCiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiUkVGRVJFTkNFIEFVRElPIOKAlCA8QXVkaW8gMT4gd2hpc3BlciAvIGJyZWF0aGluZXNzIC8gdm9pY2UiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiTG9hZEF1ZGlvIiwKICAgICAgICAiY25yX2lkIjogImNvbWZ5LWNvcmUiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFsKICAgICAgICAicmVmZXJlbmNlX3doaXNwZXIud2F2IgogICAgICBdCiAgICB9LAogICAgewogICAgICAiaWQiOiA5MDAsCiAgICAgICJ0eXBlIjogIkgzU0xBQXR0ZW50aW9uIiwKICAgICAgInBvcyI6IFsKICAgICAgICA5NjAsCiAgICAgICAgODIwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAyNjIKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDE0LAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAibW9kZWwiLAogICAgICAgICAgInR5cGUiOiAiTU9ERUwiLAogICAgICAgICAgImxpbmsiOiAyCiAgICAgICAgfQogICAgICBdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJNT0RFTCIsCiAgICAgICAgICAidHlwZSI6ICJNT0RFTCIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDE0CiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiSDMgU0xBIEF0dGVudGlvbiAwLjkgLyA2NCIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJIM1NMQUF0dGVudGlvbiIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgIDAuOSwKICAgICAgICAiNjQiLAogICAgICAgIDgxOTIsCiAgICAgICAgMCwKICAgICAgICB0cnVlLAogICAgICAgIHRydWUKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTMxLAogICAgICAidHlwZSI6ICJNaW5pTWF4SDNSZWZlcmVuY2VUb1ZpZGVvIiwKICAgICAgInBvcyI6IFsKICAgICAgICAxNDIwLAogICAgICAgIDcwMAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA1MjAsCiAgICAgICAgNjIwCiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAxNSwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImNsaXAiLAogICAgICAgICAgInR5cGUiOiAiQ0xJUCIsCiAgICAgICAgICAibGluayI6IDMKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInZhZSIsCiAgICAgICAgICAidHlwZSI6ICJWQUUiLAogICAgICAgICAgImxpbmsiOiA0CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJhdWRpb192YWUiLAogICAgICAgICAgInR5cGUiOiAiVkFFIiwKICAgICAgICAgICJsaW5rIjogNQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAicHJvbXB0IiwKICAgICAgICAgICJ0eXBlIjogIlNUUklORyIsCiAgICAgICAgICAibGluayI6IDYsCiAgICAgICAgICAid2lkZ2V0IjogewogICAgICAgICAgICAibmFtZSI6ICJwcm9tcHQiCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ3aWR0aCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmsiOiA3LAogICAgICAgICAgIndpZGdldCI6IHsKICAgICAgICAgICAgIm5hbWUiOiAid2lkdGgiCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJoZWlnaHQiLAogICAgICAgICAgInR5cGUiOiAiSU5UIiwKICAgICAgICAgICJsaW5rIjogOCwKICAgICAgICAgICJ3aWRnZXQiOiB7CiAgICAgICAgICAgICJuYW1lIjogImhlaWdodCIKICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImxlbmd0aCIsCiAgICAgICAgICAidHlwZSI6ICJJTlQiLAogICAgICAgICAgImxpbmsiOiA5LAogICAgICAgICAgIndpZGdldCI6IHsKICAgICAgICAgICAgIm5hbWUiOiAibGVuZ3RoIgogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAicmVmX2ltYWdlcyIsCiAgICAgICAgICAidHlwZSI6ICJDT01GWV9BVVRPR1JPV19WMyIsCiAgICAgICAgICAibGluayI6IG51bGwKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInJlZl92aWRlb3MiLAogICAgICAgICAgInR5cGUiOiAiQ09NRllfQVVUT0dST1dfVjMiLAogICAgICAgICAgImxpbmsiOiBudWxsCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJyZWZfdmlkZW9fYXVkaW9zIiwKICAgICAgICAgICJ0eXBlIjogIkNPTUZZX0FVVE9HUk9XX1YzIiwKICAgICAgICAgICJsaW5rIjogbnVsbAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAicmVmX2F1ZGlvcyIsCiAgICAgICAgICAidHlwZSI6ICJDT01GWV9BVVRPR1JPV19WMyIsCiAgICAgICAgICAibGluayI6IG51bGwKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJsYWJlbCI6ICJyZWZfaW1hZ2VfMCIsCiAgICAgICAgICAibmFtZSI6ICJyZWZfaW1hZ2VzLnJlZl9pbWFnZV8wIiwKICAgICAgICAgICJzaGFwZSI6IDcsCiAgICAgICAgICAidHlwZSI6ICJJTUFHRSIsCiAgICAgICAgICAibGluayI6IDEwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAicmVmX3ZpZGVvXzAiLAogICAgICAgICAgIm5hbWUiOiAicmVmX3ZpZGVvcy5yZWZfdmlkZW9fMCIsCiAgICAgICAgICAic2hhcGUiOiA3LAogICAgICAgICAgInR5cGUiOiAiSU1BR0UiLAogICAgICAgICAgImxpbmsiOiAxMgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImxhYmVsIjogInJlZl9hdWRpb18wIiwKICAgICAgICAgICJuYW1lIjogInJlZl9hdWRpb3MucmVmX2F1ZGlvXzAiLAogICAgICAgICAgInNoYXBlIjogNywKICAgICAgICAgICJ0eXBlIjogIkFVRElPIiwKICAgICAgICAgICJsaW5rIjogMTMKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInBvc2l0aXZlIiwKICAgICAgICAgICJ0eXBlIjogIkNPTkRJVElPTklORyIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDE3CiAgICAgICAgICBdLAogICAgICAgICAgInNsb3RfaW5kZXgiOiAwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJMQVRFTlQiLAogICAgICAgICAgInR5cGUiOiAiTEFURU5UIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMjIKICAgICAgICAgIF0sCiAgICAgICAgICAic2xvdF9pbmRleCI6IDEKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJNaW5pTWF4IEgzIFJlZjJWQSDigJQgUGljdHVyZSArIE1vdGlvbiBWaWRlbyArIFN0YW5kYWxvbmUgQXVkaW8iLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiTWluaU1heEgzUmVmZXJlbmNlVG9WaWRlbyIsCiAgICAgICAgImNucl9pZCI6ICJjb21meS1jb3JlIgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgIiIsCiAgICAgICAgMTM0NCwKICAgICAgICA3NjgsCiAgICAgICAgMTI0LAogICAgICAgICJtYXRjaCIKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTQyLAogICAgICAidHlwZSI6ICJNaW5pTWF4SDNTaWdtYVNoaWZ0IiwKICAgICAgInBvcyI6IFsKICAgICAgICAxNDIwLAogICAgICAgIDEzNjAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDE1MAogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogMTYsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJtb2RlbCIsCiAgICAgICAgICAidHlwZSI6ICJNT0RFTCIsCiAgICAgICAgICAibGluayI6IDE0CiAgICAgICAgfQogICAgICBdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJNT0RFTCIsCiAgICAgICAgICAidHlwZSI6ICJNT0RFTCIsCiAgICAgICAgICAibGlua3MiOiBbCiAgICAgICAgICAgIDE1LAogICAgICAgICAgICAxNgogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIk1pbmlNYXhIM1NpZ21hU2hpZnQiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiTWluaU1heEgzU2lnbWFTaGlmdCIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogWwogICAgICAgIDEyLjAsCiAgICAgICAgMy4wCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEyNCwKICAgICAgInR5cGUiOiAiQmFzaWNTY2hlZHVsZXIiLAogICAgICAicG9zIjogWwogICAgICAgIDE4ODAsCiAgICAgICAgMTM2MAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA0MDAsCiAgICAgICAgMTc4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAxNywKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIm1vZGVsIiwKICAgICAgICAgICJ0eXBlIjogIk1PREVMIiwKICAgICAgICAgICJsaW5rIjogMTUKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIlNJR01BUyIsCiAgICAgICAgICAidHlwZSI6ICJTSUdNQVMiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAyMQogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIjQtc3RlcCBzaW1wbGUgc2NoZWR1bGVyIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIkJhc2ljU2NoZWR1bGVyIgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgInNpbXBsZSIsCiAgICAgICAgNCwKICAgICAgICAxLjAKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTI2LAogICAgICAidHlwZSI6ICJCYXNpY0d1aWRlciIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgMTg4MCwKICAgICAgICA3MDAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDExOAogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogMTgsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJtb2RlbCIsCiAgICAgICAgICAidHlwZSI6ICJNT0RFTCIsCiAgICAgICAgICAibGluayI6IDE2CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJjb25kaXRpb25pbmciLAogICAgICAgICAgInR5cGUiOiAiQ09ORElUSU9OSU5HIiwKICAgICAgICAgICJsaW5rIjogMTcKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIkdVSURFUiIsCiAgICAgICAgICAidHlwZSI6ICJHVUlERVIiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAxOQogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkJhc2ljR3VpZGVyIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIkJhc2ljR3VpZGVyIgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbXQogICAgfSwKICAgIHsKICAgICAgImlkIjogMTI1LAogICAgICAidHlwZSI6ICJTYW1wbGVyQ3VzdG9tQWR2YW5jZWQiLAogICAgICAicG9zIjogWwogICAgICAgIDIzNDAsCiAgICAgICAgNzAwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAxOTAKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDE5LAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAibm9pc2UiLAogICAgICAgICAgInR5cGUiOiAiTk9JU0UiLAogICAgICAgICAgImxpbmsiOiAxOAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiZ3VpZGVyIiwKICAgICAgICAgICJ0eXBlIjogIkdVSURFUiIsCiAgICAgICAgICAibGluayI6IDE5CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJzYW1wbGVyIiwKICAgICAgICAgICJ0eXBlIjogIlNBTVBMRVIiLAogICAgICAgICAgImxpbmsiOiAyMAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAic2lnbWFzIiwKICAgICAgICAgICJ0eXBlIjogIlNJR01BUyIsCiAgICAgICAgICAibGluayI6IDIxCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJsYXRlbnRfaW1hZ2UiLAogICAgICAgICAgInR5cGUiOiAiTEFURU5UIiwKICAgICAgICAgICJsaW5rIjogMjIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIm91dHB1dCIsCiAgICAgICAgICAidHlwZSI6ICJMQVRFTlQiLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAyMywKICAgICAgICAgICAgMjUKICAgICAgICAgIF0sCiAgICAgICAgICAic2xvdF9pbmRleCI6IDAKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImRlbm9pc2VkX291dHB1dCIsCiAgICAgICAgICAidHlwZSI6ICJMQVRFTlQiLAogICAgICAgICAgImxpbmtzIjogbnVsbCwKICAgICAgICAgICJzbG90X2luZGV4IjogMQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIlNhbXBsZXJDdXN0b21BZHZhbmNlZCIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJTYW1wbGVyQ3VzdG9tQWR2YW5jZWQiCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMjEsCiAgICAgICJ0eXBlIjogIlZBRURlY29kZUF1ZGlvIiwKICAgICAgInBvcyI6IFsKICAgICAgICAyODAwLAogICAgICAgIDcwMAogICAgICBdLAogICAgICAic2l6ZSI6IFsKICAgICAgICA0MDAsCiAgICAgICAgMTE4CiAgICAgIF0sCiAgICAgICJmbGFncyI6IHt9LAogICAgICAib3JkZXIiOiAyMCwKICAgICAgIm1vZGUiOiAwLAogICAgICAiaW5wdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInNhbXBsZXMiLAogICAgICAgICAgInR5cGUiOiAiTEFURU5UIiwKICAgICAgICAgICJsaW5rIjogMjMKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogInZhZSIsCiAgICAgICAgICAidHlwZSI6ICJWQUUiLAogICAgICAgICAgImxpbmsiOiAyNAogICAgICAgIH0KICAgICAgXSwKICAgICAgIm91dHB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiQVVESU8iLAogICAgICAgICAgInR5cGUiOiAiQVVESU8iLAogICAgICAgICAgImxpbmtzIjogWwogICAgICAgICAgICAyOAogICAgICAgICAgXQogICAgICAgIH0KICAgICAgXSwKICAgICAgInRpdGxlIjogIkRlY29kZSBnZW5lcmF0ZWQgYXVkaW8iLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiVkFFRGVjb2RlQXVkaW8iCiAgICAgIH0sCiAgICAgICJ3aWRnZXRzX3ZhbHVlcyI6IFtdCiAgICB9LAogICAgewogICAgICAiaWQiOiAxMjIsCiAgICAgICJ0eXBlIjogIlZBRURlY29kZSIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgMjgwMCwKICAgICAgICA4NjAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDExOAogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogMjEsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJzYW1wbGVzIiwKICAgICAgICAgICJ0eXBlIjogIkxBVEVOVCIsCiAgICAgICAgICAibGluayI6IDI1CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ2YWUiLAogICAgICAgICAgInR5cGUiOiAiVkFFIiwKICAgICAgICAgICJsaW5rIjogMjYKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIklNQUdFIiwKICAgICAgICAgICJ0eXBlIjogIklNQUdFIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMjcKICAgICAgICAgIF0KICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJEZWNvZGUgZ2VuZXJhdGVkIHZpZGVvIiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgIk5vZGUgbmFtZSBmb3IgUyZSIjogIlZBRURlY29kZSIKICAgICAgfSwKICAgICAgIndpZGdldHNfdmFsdWVzIjogW10KICAgIH0sCiAgICB7CiAgICAgICJpZCI6IDEzMCwKICAgICAgInR5cGUiOiAiQ3JlYXRlVmlkZW8iLAogICAgICAicG9zIjogWwogICAgICAgIDMyNjAsCiAgICAgICAgNzAwCiAgICAgIF0sCiAgICAgICJzaXplIjogWwogICAgICAgIDQwMCwKICAgICAgICAyMDIKICAgICAgXSwKICAgICAgImZsYWdzIjoge30sCiAgICAgICJvcmRlciI6IDIyLAogICAgICAibW9kZSI6IDAsCiAgICAgICJpbnB1dHMiOiBbCiAgICAgICAgewogICAgICAgICAgIm5hbWUiOiAiaW1hZ2VzIiwKICAgICAgICAgICJ0eXBlIjogIklNQUdFIiwKICAgICAgICAgICJsaW5rIjogMjcKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogImF1ZGlvIiwKICAgICAgICAgICJ0eXBlIjogIkFVRElPIiwKICAgICAgICAgICJsaW5rIjogMjgKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJvdXRwdXRzIjogWwogICAgICAgIHsKICAgICAgICAgICJuYW1lIjogIlZJREVPIiwKICAgICAgICAgICJ0eXBlIjogIlZJREVPIiwKICAgICAgICAgICJsaW5rcyI6IFsKICAgICAgICAgICAgMjkKICAgICAgICAgIF0sCiAgICAgICAgICAic2xvdF9pbmRleCI6IDAKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJ0aXRsZSI6ICJDcmVhdGVWaWRlbyAyNGZwcyIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJOb2RlIG5hbWUgZm9yIFMmUiI6ICJDcmVhdGVWaWRlbyIsCiAgICAgICAgImNucl9pZCI6ICJjb21meS1jb3JlIgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgMjQsCiAgICAgICAgOCwKICAgICAgICAic1JHQiIKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImlkIjogOTIsCiAgICAgICJ0eXBlIjogIlNhdmVWaWRlbyIsCiAgICAgICJwb3MiOiBbCiAgICAgICAgMzcyMCwKICAgICAgICA3MDAKICAgICAgXSwKICAgICAgInNpemUiOiBbCiAgICAgICAgNDAwLAogICAgICAgIDE3OAogICAgICBdLAogICAgICAiZmxhZ3MiOiB7fSwKICAgICAgIm9yZGVyIjogMjMsCiAgICAgICJtb2RlIjogMCwKICAgICAgImlucHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ2aWRlbyIsCiAgICAgICAgICAidHlwZSI6ICJWSURFTyIsCiAgICAgICAgICAibGluayI6IDI5CiAgICAgICAgfQogICAgICBdLAogICAgICAib3V0cHV0cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibmFtZSI6ICJ2aWRlbyIsCiAgICAgICAgICAidHlwZSI6ICJWSURFTyIsCiAgICAgICAgICAibGlua3MiOiBudWxsLAogICAgICAgICAgInNsb3RfaW5kZXgiOiAwCiAgICAgICAgfQogICAgICBdLAogICAgICAidGl0bGUiOiAiU0FWRSDigJQgMDVCIFZJREVPICsgU0VQQVJBVEUgQVVESU8iLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiTm9kZSBuYW1lIGZvciBTJlIiOiAiU2F2ZVZpZGVvIgogICAgICB9LAogICAgICAid2lkZ2V0c192YWx1ZXMiOiBbCiAgICAgICAgInZpZGVvLzA1Ql9GVVNFRF9IM19SRUZfVklERU9fUExVU19TRVBBUkFURV9BVURJTyIsCiAgICAgICAgImF1dG8iLAogICAgICAgICJhdXRvIgogICAgICBdCiAgICB9CiAgXSwKICAibGlua3MiOiBbCiAgICBbCiAgICAgIDEsCiAgICAgIDEzMywKICAgICAgMCwKICAgICAgMTMyLAogICAgICAxLAogICAgICAiRkxPQVQiCiAgICBdLAogICAgWwogICAgICAyLAogICAgICAxMjcsCiAgICAgIDAsCiAgICAgIDkwMCwKICAgICAgMCwKICAgICAgIk1PREVMIgogICAgXSwKICAgIFsKICAgICAgMywKICAgICAgMTI4LAogICAgICAwLAogICAgICAxMzEsCiAgICAgIDAsCiAgICAgICJDTElQIgogICAgXSwKICAgIFsKICAgICAgNCwKICAgICAgMTE5LAogICAgICAwLAogICAgICAxMzEsCiAgICAgIDEsCiAgICAgICJWQUUiCiAgICBdLAogICAgWwogICAgICA1LAogICAgICAxMjAsCiAgICAgIDAsCiAgICAgIDEzMSwKICAgICAgMiwKICAgICAgIlZBRSIKICAgIF0sCiAgICBbCiAgICAgIDYsCiAgICAgIDEsCiAgICAgIDAsCiAgICAgIDEzMSwKICAgICAgMywKICAgICAgIlNUUklORyIKICAgIF0sCiAgICBbCiAgICAgIDcsCiAgICAgIDExNSwKICAgICAgMCwKICAgICAgMTMxLAogICAgICA0LAogICAgICAiSU5UIgogICAgXSwKICAgIFsKICAgICAgOCwKICAgICAgMTE1LAogICAgICAxLAogICAgICAxMzEsCiAgICAgIDUsCiAgICAgICJJTlQiCiAgICBdLAogICAgWwogICAgICA5LAogICAgICAxMzIsCiAgICAgIDEsCiAgICAgIDEzMSwKICAgICAgNiwKICAgICAgIklOVCIKICAgIF0sCiAgICBbCiAgICAgIDEwLAogICAgICA5MDEsCiAgICAgIDAsCiAgICAgIDEzMSwKICAgICAgMTEsCiAgICAgICJJTUFHRSIKICAgIF0sCiAgICBbCiAgICAgIDExLAogICAgICA5MDIsCiAgICAgIDAsCiAgICAgIDkwMywKICAgICAgMCwKICAgICAgIlZJREVPIgogICAgXSwKICAgIFsKICAgICAgMTIsCiAgICAgIDkwMywKICAgICAgMCwKICAgICAgMTMxLAogICAgICAxMiwKICAgICAgIklNQUdFIgogICAgXSwKICAgIFsKICAgICAgMTMsCiAgICAgIDkwNCwKICAgICAgMCwKICAgICAgMTMxLAogICAgICAxMywKICAgICAgIkFVRElPIgogICAgXSwKICAgIFsKICAgICAgMTQsCiAgICAgIDkwMCwKICAgICAgMCwKICAgICAgMTQyLAogICAgICAwLAogICAgICAiTU9ERUwiCiAgICBdLAogICAgWwogICAgICAxNSwKICAgICAgMTQyLAogICAgICAwLAogICAgICAxMjQsCiAgICAgIDAsCiAgICAgICJNT0RFTCIKICAgIF0sCiAgICBbCiAgICAgIDE2LAogICAgICAxNDIsCiAgICAgIDAsCiAgICAgIDEyNiwKICAgICAgMCwKICAgICAgIk1PREVMIgogICAgXSwKICAgIFsKICAgICAgMTcsCiAgICAgIDEzMSwKICAgICAgMCwKICAgICAgMTI2LAogICAgICAxLAogICAgICAiQ09ORElUSU9OSU5HIgogICAgXSwKICAgIFsKICAgICAgMTgsCiAgICAgIDEyOSwKICAgICAgMCwKICAgICAgMTI1LAogICAgICAwLAogICAgICAiTk9JU0UiCiAgICBdLAogICAgWwogICAgICAxOSwKICAgICAgMTI2LAogICAgICAwLAogICAgICAxMjUsCiAgICAgIDEsCiAgICAgICJHVUlERVIiCiAgICBdLAogICAgWwogICAgICAyMCwKICAgICAgMTM1LAogICAgICAwLAogICAgICAxMjUsCiAgICAgIDIsCiAgICAgICJTQU1QTEVSIgogICAgXSwKICAgIFsKICAgICAgMjEsCiAgICAgIDEyNCwKICAgICAgMCwKICAgICAgMTI1LAogICAgICAzLAogICAgICAiU0lHTUFTIgogICAgXSwKICAgIFsKICAgICAgMjIsCiAgICAgIDEzMSwKICAgICAgMSwKICAgICAgMTI1LAogICAgICA0LAogICAgICAiTEFURU5UIgogICAgXSwKICAgIFsKICAgICAgMjMsCiAgICAgIDEyNSwKICAgICAgMCwKICAgICAgMTIxLAogICAgICAwLAogICAgICAiTEFURU5UIgogICAgXSwKICAgIFsKICAgICAgMjQsCiAgICAgIDEyMCwKICAgICAgMCwKICAgICAgMTIxLAogICAgICAxLAogICAgICAiVkFFIgogICAgXSwKICAgIFsKICAgICAgMjUsCiAgICAgIDEyNSwKICAgICAgMCwKICAgICAgMTIyLAogICAgICAwLAogICAgICAiTEFURU5UIgogICAgXSwKICAgIFsKICAgICAgMjYsCiAgICAgIDExOSwKICAgICAgMCwKICAgICAgMTIyLAogICAgICAxLAogICAgICAiVkFFIgogICAgXSwKICAgIFsKICAgICAgMjcsCiAgICAgIDEyMiwKICAgICAgMCwKICAgICAgMTMwLAogICAgICAwLAogICAgICAiSU1BR0UiCiAgICBdLAogICAgWwogICAgICAyOCwKICAgICAgMTIxLAogICAgICAwLAogICAgICAxMzAsCiAgICAgIDEsCiAgICAgICJBVURJTyIKICAgIF0sCiAgICBbCiAgICAgIDI5LAogICAgICAxMzAsCiAgICAgIDAsCiAgICAgIDkyLAogICAgICAwLAogICAgICAiVklERU8iCiAgICBdCiAgXSwKICAiZ3JvdXBzIjogWwogICAgewogICAgICAiaWQiOiAxLAogICAgICAidGl0bGUiOiAiUkVGRVJFTkNFIElOUFVUUyDigJQgUGljdHVyZSAxIC8gVmlkZW8gMSAvIEF1ZGlvIDEiLAogICAgICAiYm91bmRpbmciOiBbCiAgICAgICAgNDcwLAogICAgICAgIDc4MCwKICAgICAgICA4MDAsCiAgICAgICAgOTMwCiAgICAgIF0sCiAgICAgICJjb2xvciI6ICIjM2Y3ODllIiwKICAgICAgImZvbnRfc2l6ZSI6IDI0LAogICAgICAiZmxhZ3MiOiB7fQogICAgfSwKICAgIHsKICAgICAgImlkIjogMiwKICAgICAgInRpdGxlIjogIkZVU0VEIEgzIFJFRjJWQSA0LVNURVAgU0xBIiwKICAgICAgImJvdW5kaW5nIjogWwogICAgICAgIDEzODAsCiAgICAgICAgNjUwLAogICAgICAgIDE0MDAsCiAgICAgICAgOTMwCiAgICAgIF0sCiAgICAgICJjb2xvciI6ICIjOGE2ZDNiIiwKICAgICAgImZvbnRfc2l6ZSI6IDI0LAogICAgICAiZmxhZ3MiOiB7fQogICAgfSwKICAgIHsKICAgICAgImlkIjogMywKICAgICAgInRpdGxlIjogIkRFQ09ERSArIFNBVkUiLAogICAgICAiYm91bmRpbmciOiBbCiAgICAgICAgMjc2MCwKICAgICAgICA2NTAsCiAgICAgICAgMTQwMCwKICAgICAgICAzODAKICAgICAgXSwKICAgICAgImNvbG9yIjogIiM1OTZiNGQiLAogICAgICAiZm9udF9zaXplIjogMjQsCiAgICAgICJmbGFncyI6IHt9CiAgICB9CiAgXSwKICAiY29uZmlnIjoge30sCiAgImV4dHJhIjogewogICAgImRzIjogewogICAgICAic2NhbGUiOiAwLjcyLAogICAgICAib2Zmc2V0IjogWwogICAgICAgIDEyMCwKICAgICAgICAxMDAKICAgICAgXQogICAgfSwKICAgICJmcm9udGVuZFZlcnNpb24iOiAiMS40NC4xOSIsCiAgICAid29ya2Zsb3dfbm90ZSI6ICIwNUI6IFJlZmVyZW5jZSB2aWRlbyBzdXBwbGllcyBtb3Rpb24vdGltaW5nOyBzZXBhcmF0ZSBhdWRpbyBmaWxlIHN1cHBsaWVzIHdoaXNwZXIvdm9pY2UuIFBpY3R1cmUgMSBjb250cm9scyBpZGVudGl0eS4gVXNlIHdoZW4geW91IHdhbnQgaW5kZXBlbmRlbnQgYXVkaW8gY29udHJvbC4iCiAgfSwKICAidmVyc2lvbiI6IDAuNAp9
B64_05B

"$PY" - "$WF_DIR/$WF_I2V" "$WF_DIR/$WF_REF" "$WF_DIR/$WF_REFA" "$WF_DIR/$WF_REFB" "$MODEL" "$TEXT" "$VIDEO_VAE" "$AUDIO_VAE" <<'PYCODE'
import json, sys
paths=sys.argv[1:5]
required=sys.argv[5:]
for p in paths:
    d=json.load(open(p, encoding="utf-8"))
    s=json.dumps(d)
    for item in required:
        if item not in s:
            raise SystemExit(f"{p}: required file name not present: {item}")
    print("validated:", p)

# RefAV-specific structure checks.
a=json.load(open(paths[2], encoding="utf-8"))
b=json.load(open(paths[3], encoding="utf-8"))
sa=json.dumps(a)
sb=json.dumps(b)
for token in ["LoadVideo","GetVideoComponents","MiniMaxH3ReferenceToVideo"]:
    if token not in sa:
        raise SystemExit(f"05A missing node token: {token}")
for token in ["LoadVideo","GetVideoComponents","LoadAudio","MiniMaxH3ReferenceToVideo"]:
    if token not in sb:
        raise SystemExit(f"05B missing node token: {token}")
print("RefAV workflow structure OK")
PYCODE

green "  ✓ official + 05A + 05B workflows installed"

# -----------------------------------------------------------------------------
# 8. Safe port handoff
# -----------------------------------------------------------------------------
echo "[8/10] Port $PORT handoff"

pids="$(lsof -ti tcp:"$PORT" 2>/dev/null || true)"
if [[ -n "$pids" ]]; then
  for pid in $pids; do
    cmd="$(tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null || true)"
    cwd="$(readlink -f "/proc/$pid/cwd" 2>/dev/null || true)"
    if [[ "$cmd" == *"main.py"* && "$cwd" == "$ROOT"/ComfyUI* ]]; then
      echo "  stopping existing ComfyUI PID $pid ($cwd)"
      kill "$pid" 2>/dev/null || true
    else
      die "Port $PORT is occupied by unrelated PID $pid ($cwd)"
    fi
  done
  for _ in $(seq 1 30); do
    [[ -z "$(lsof -ti tcp:"$PORT" 2>/dev/null || true)" ]] && break
    sleep 1
  done
fi

[[ -z "$(lsof -ti tcp:"$PORT" 2>/dev/null || true)" ]] || die "Could not free port $PORT"

# -----------------------------------------------------------------------------
# 9. Start and validate
# -----------------------------------------------------------------------------
echo "[9/10] Start ComfyUI"

RUNTIME_LOG="$RUNTIME_DIR/comfy_$(date +%Y%m%d_%H%M%S).log"
cd "$COMFY"
nohup "$PY" main.py \
  --listen 0.0.0.0 \
  --port "$PORT" \
  --preview-method auto \
  --enable-cors-header \
  --reserve-vram 4 \
  --cache-none \
  > "$RUNTIME_LOG" 2>&1 &
PID=$!
echo "$PID" > "$COMFY/h3_fused_refav.pid"

ready=0
for _ in $(seq 1 180); do
  if ! kill -0 "$PID" 2>/dev/null; then
    tail -160 "$RUNTIME_LOG" || true
    die "ComfyUI process exited during startup"
  fi
  if curl -fsS "http://127.0.0.1:$PORT/system_stats" >/tmp/h3_fused_system_stats.json 2>/dev/null; then
    ready=1
    break
  fi
  sleep 1
done

[[ "$ready" == "1" ]] || {
  tail -160 "$RUNTIME_LOG" || true
  die "ComfyUI did not become ready within 180 seconds"
}

# Validate required node names from object_info.
curl -fsS "http://127.0.0.1:$PORT/object_info" -o /tmp/h3_fused_object_info.json
"$PY" - <<'PYCODE'
import json
d=json.load(open("/tmp/h3_fused_object_info.json"))
names=set(d)
required_core=["MiniMaxH3ImageToVideo","MiniMaxH3ReferenceToVideo","UNETLoader","LoadVideo","GetVideoComponents","LoadAudio"]
missing=[x for x in required_core if x not in names]
if missing:
    raise SystemExit("Missing required core nodes: " + ", ".join(missing))
sla=[x for x in names if "SLA" in x.upper() and "H3" in x.upper()]
print("H3 SLA-like nodes:", sla[:20])
if not sla:
    raise SystemExit("H3 SLA attention node was not registered")
print("Required MiniMax H3 nodes OK")
PYCODE

green "  ✓ ComfyUI + H3 + Ref2VA + SLA registered"

# -----------------------------------------------------------------------------
# 10. Launchers / summary
# -----------------------------------------------------------------------------
echo "[10/10] Save launchers"

cat > "$COMFY/start_h3_fused_refav.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$COMFY"
exec "$PY" main.py --listen 0.0.0.0 --port "$PORT" --preview-method auto --enable-cors-header --reserve-vram 4 --cache-none
EOF
chmod +x "$COMFY/start_h3_fused_refav.sh"

cat > "$COMFY/restart_h3_fused_refav.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
pids=\$(lsof -ti tcp:"$PORT" 2>/dev/null || true)
[[ -z "\$pids" ]] || kill \$pids 2>/dev/null || true
sleep 2
cd "$COMFY"
nohup "$PY" main.py --listen 0.0.0.0 --port "$PORT" --preview-method auto --enable-cors-header --reserve-vram 4 --cache-none > "$RUNTIME_DIR/comfy_restart.log" 2>&1 &
echo "Started H3 Fused RefAV on port $PORT"
EOF
chmod +x "$COMFY/restart_h3_fused_refav.sh"

trap - ERR
trap - EXIT

echo
echo "================================================================="
green " READY — MiniMax H3 FUSED RefAV COMPLETE v1"
echo "================================================================="
echo "Environment:"
echo "  $COMFY"
echo
echo "Model:"
echo "  $MODEL"
echo
echo "Workflows:"
echo "  $WF_I2V   <- I2V / FL2V 4-step SLA"
echo "  $WF_REF   <- Official Ref2VA 4-step SLA"
echo "  $WF_REFA  <- 05A: ONE MP4 = motion + embedded audio"
echo "  $WF_REFB  <- 05B: video = motion / separate audio = voice"
echo
echo "Recommended baseline:"
echo "  sampler: res_multistep"
echo "  scheduler: simple"
echo "  steps: 4"
echo "  video shift: 12"
echo "  audio shift: 3"
echo "  SLA: sparsity 0.90 / block 64 / protect audio ON"
echo
echo "Setup log:"
echo "  $SETUP_LOG"
echo "Runtime log:"
echo "  $RUNTIME_LOG"
echo
echo "Open RunPod port 8188 and load 05A or 05B for RefAV generation."
echo "================================================================="
